# Description
# ===========
# This playbook creates the pre-requisites needed for an Azure Red Hat OpenShift cluster
# https://learn.microsoft.com/en-us/azure/openshift/tutorial-create-cluster
# 
# Make sure you have at least 40-50 vCPUs in your target deployment region. 
# https://docs.microsoft.com/en-us/azure/azure-portal/supportability/regional-quota-requests
# az vm list-usage --location "Central US" --output table | grep "Total Regional vCPUs" 
# 
- hosts: localhost
  connection: local
  vars:
    SUBSRIPTION: XXXXXX

  tasks:
  - name: "Set Subscription"
    command:
      cmd: az account set --subscription {{ SUBSCRIPTION }}
  
  - name: "Register the Microsoft.Compute resource provider"
    command:
      cmd: az provider register -n Microsoft.Compute --wait

  - name: "Register the Microsoft.Storage resource provider"
    command:
      cmd: az provider register -n Microsoft.Storage --wait
  
  - name: "Register the Microsoft.Authorization resource provider"
    command:
      cmd: az provider register -n Microsoft.Authorization --wait

  - name: "Register ARO preview features"
    command:
      cmd: az feature register --namespace Microsoft.RedHatOpenShift --name preview

  - name: "Register the Microsoft.RedHatOpenShift resource provider"
    command:
      cmd: az provider register -n Microsoft.RedHatOpenShift --wait