# Description
# ===========
# This playbook deeltes an Azure Red Hat OpenShift cluster
# https://learn.microsoft.com/en-us/azure/openshift/tutorial-delete-cluster#delete-the-cluster

- hosts: localhost
  connection: local

  vars_prompt:
  - name: answer
    prompt: "Do you really want to delete the OpenShift cluster? y/n?"

  vars:
    LOCATION: swedencentral
    RESOURCEGROUP: jtudelag-aro
    CLUSTER: jtudelag-cluster
    DOMAIN: jtudelag.redhat.com
    MASTER_SIZE : Standard_D8s_v3
    WORKER_SIZE : Standard_D4s_v3
    WORKER_COUNT: 3
    DISK_SIZE: 128

  tasks:
  - name: Delete ARO cluster and the Azure Resource Group
    block:
      - name: "Delete ARO cluster"
        command: az aro delete \
                 --yes \
                 --resource-group {{ RESOURCEGROUP }} \
                 --name {{ CLUSTER}}
            
      - name: "Delete Resource Group"
        command: az group delete \
                 --yes \
                 --name {{ RESOURCEGROUP }}
    when:
      - answer == "y"

  